name: "Validate Gradle Wrapper"

on:
  push:
  pull_request:

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: gradle/actions/wrapper-validation@v6
        with:
          allow-checksums: fbd8f66b83e1a46057f8fdd98e734c2c077aab78daf2c1f7bf29808fcd740b74
